swagger: "2.0"
info:
  description: |
    This is MyMusic API.
    To try operations you have to obtain a JSON Web Token, fill the api_key field and press explore.
  version: "1.0.0"
  title: MyMusic
  termsOfService: http://helloreverb.com/terms/
  contact:
    name: Spiros Kabasakalis
    email: kabasakalis@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: api.app.me:3000
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/vnd.siren+json
paths: